name: Go CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: api/go.mod

      - name: Verify frontend placeholder exists
        run: |
          if [ ! -f cmd/web-licensed/frontend/index.html ]; then
            echo "Creating frontend placeholder for CI"
            mkdir -p cmd/web-licensed/frontend
            echo '<!DOCTYPE html><html><body>CI Build Placeholder</body></html>' > cmd/web-licensed/frontend/index.html
          fi
          ls -la cmd/web-licensed/frontend/

      - name: Cache modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('api/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -v 